import type { Base } from "./types";
import { CONSULTOR_ID } from "./marca";

const C = CONSULTOR_ID;

/**
 * Dados de demonstração. Ficam num ficheiro à parte para se poderem apagar
 * quando o consultor começar a usar a plataforma a sério.
 */
export function semente(): Base {
  return {
    clientes: [
      {
        id: "cli_ana",
        consultorId: C,
        nome: "Ana Salgueiro",
        email: "ana.salgueiro@exemplo.pt",
        telefone: "+351 913 220 118",
        pais: "Portugal",
        idioma: "pt",
        preferencias: {
          estilo: "Lua de mel, praia e gastronomia, sem pressas",
          ritmo: "tranquilo",
          alojamento: "luxo",
          interesses: ["Praia", "Gastronomia", "Spa", "Pôr do sol"],
          restricoes: "Alergia a marisco. Não gosta de voos com escala longa.",
          orcamentoTipico: 8000,
        },
        notas:
          "Casou em maio. Muito responsiva por WhatsApp, quase nunca por email.",
        criadoEm: "2026-02-11",
      },
      {
        id: "cli_bruno",
        consultorId: C,
        nome: "Bruno Teixeira",
        email: "bruno.teixeira@exemplo.pt",
        telefone: "+351 936 004 771",
        pais: "Portugal",
        idioma: "pt",
        preferencias: {
          estilo: "Aventura, trilhos, fotografia de paisagem",
          ritmo: "intenso",
          alojamento: "boutique",
          interesses: ["Trekking", "Fotografia", "Montanha", "Vida selvagem"],
          restricoes: "Vegetariano.",
          orcamentoTipico: 4500,
        },
        notas: "Viaja sempre em setembro/outubro. Decide rápido.",
        criadoEm: "2025-09-03",
      },
      {
        id: "cli_carla",
        consultorId: C,
        nome: "Carla e Nuno Ferreira",
        email: "carla.ferreira@exemplo.pt",
        telefone: "+351 917 882 003",
        pais: "Portugal",
        idioma: "pt",
        preferencias: {
          estilo: "Família com dois filhos (6 e 9 anos)",
          ritmo: "equilibrado",
          alojamento: "familiar",
          interesses: ["Parques", "Praia", "Cultura leve", "Piscina"],
          restricoes: "Filho mais novo enjoa em viagens de carro longas.",
          orcamentoTipico: 6000,
        },
        notas: "Reservam sempre com 4-5 meses de antecedência.",
        criadoEm: "2025-06-21",
      },
      {
        id: "cli_diogo",
        consultorId: C,
        nome: "Diogo Mendes",
        email: "d.mendes@exemplo.com",
        telefone: "+351 961 447 220",
        pais: "Portugal",
        idioma: "en",
        preferencias: {
          estilo: "Viagens de trabalho com fim-de-semana esticado",
          ritmo: "equilibrado",
          alojamento: "boutique",
          interesses: ["Cidade", "Arquitetura", "Cafés", "Museus"],
          restricoes: "Precisa sempre de wifi bom e check-out tardio.",
          orcamentoTipico: 2500,
        },
        notas: "Prefere comunicação em inglês. Trabalha em fintech.",
        criadoEm: "2025-11-14",
      },
      {
        id: "cli_ines",
        consultorId: C,
        nome: "Inês Rocha",
        email: "ines.rocha@exemplo.pt",
        telefone: "+351 925 771 903",
        pais: "Portugal",
        idioma: "pt",
        preferencias: {
          estilo: "Viagem entre amigas, cultura e vida noturna",
          ritmo: "intenso",
          alojamento: "economico",
          interesses: ["Cultura", "Mercados", "Música", "Compras"],
          restricoes: "Orçamento apertado, sensível ao preço dos voos.",
          orcamentoTipico: 1800,
        },
        notas: "Primeira vez que trabalha connosco — veio por recomendação da Ana.",
        criadoEm: "2026-07-30",
      },
      {
        id: "cli_helena",
        consultorId: C,
        nome: "Helena Vasconcelos",
        email: "helena.v@exemplo.pt",
        telefone: "+351 939 112 447",
        pais: "Portugal",
        idioma: "pt",
        preferencias: {
          estilo: "Viagens culturais lentas, sozinha ou com uma amiga",
          ritmo: "tranquilo",
          alojamento: "boutique",
          interesses: ["História", "Arte", "Jardins", "Comboio"],
          restricoes: "Evita voos longos. Prefere comboio na Europa.",
          orcamentoTipico: 3200,
        },
        notas: "Cliente desde 2023. Já fez 4 viagens connosco.",
        criadoEm: "2023-04-09",
      },
    ],

    pedidos: [
      {
        id: "ped_ines_marrocos",
        consultorId: C,
        clienteId: "cli_ines",
        destino: "Marrocos",
        dataInicio: "2026-10-16",
        dataFim: "2026-10-22",
        adultos: 4,
        criancas: 0,
        orcamento: 1800,
        mensagem:
          "Somos quatro amigas, queremos Marraquexe e talvez o deserto. Uma semana em outubro. Podemos gastar até 450€ cada, voos incluídos?",
        estado: "novo",
        origem: "formulario",
        criadoEm: "2026-08-26",
      },
      {
        id: "ped_diogo_copenhaga",
        consultorId: C,
        clienteId: "cli_diogo",
        destino: "Copenhaga",
        dataInicio: "2026-09-24",
        dataFim: "2026-09-28",
        adultos: 1,
        criancas: 0,
        orcamento: 2200,
        mensagem:
          "Conference in Copenhagen on the 24th-25th. I'd like to stay through the weekend. Something design-led, walkable.",
        estado: "novo",
        origem: "email",
        criadoEm: "2026-08-24",
      },
      {
        id: "ped_ana_maldivas",
        consultorId: C,
        clienteId: "cli_ana",
        destino: "Maldivas",
        dataInicio: "2026-11-07",
        dataFim: "2026-11-17",
        adultos: 2,
        criancas: 0,
        orcamento: 9000,
        mensagem:
          "A nossa lua de mel a sério, finalmente! Dez dias, queremos um overwater e muito descanso.",
        estado: "em_proposta",
        origem: "whatsapp",
        criadoEm: "2026-08-12",
      },
      {
        id: "ped_bruno_dolomitas",
        consultorId: C,
        clienteId: "cli_bruno",
        destino: "Dolomitas",
        dataInicio: "2026-09-19",
        dataFim: "2026-09-26",
        adultos: 2,
        criancas: 0,
        orcamento: 4200,
        mensagem:
          "Uma semana de trilhos nas Dolomitas, com um ou dois rifugios pelo meio.",
        estado: "ganho",
        origem: "referencia",
        criadoEm: "2026-06-02",
      },
      {
        id: "ped_carla_creta",
        consultorId: C,
        clienteId: "cli_carla",
        destino: "Creta",
        dataInicio: "2026-07-11",
        dataFim: "2026-07-21",
        adultos: 2,
        criancas: 2,
        orcamento: 6200,
        mensagem: "Dez dias em Creta com os miúdos, em julho.",
        estado: "ganho",
        origem: "formulario",
        criadoEm: "2026-02-18",
      },
      {
        id: "ped_helena_toscana",
        consultorId: C,
        clienteId: "cli_helena",
        destino: "Toscana",
        dataInicio: "2026-05-04",
        dataFim: "2026-05-12",
        adultos: 2,
        criancas: 0,
        orcamento: 3400,
        mensagem: "Toscana de comboio e carro, com calma, na primavera.",
        estado: "ganho",
        origem: "email",
        criadoEm: "2026-01-08",
      },
      {
        id: "ped_helena_japao",
        consultorId: C,
        clienteId: "cli_helena",
        destino: "Japão",
        dataInicio: "2027-04-03",
        dataFim: "2027-04-18",
        adultos: 2,
        criancas: 0,
        orcamento: 7500,
        mensagem:
          "Estive a pensar no Japão para a próxima primavera, na altura das cerejeiras. É muito cedo para falar?",
        estado: "novo",
        origem: "whatsapp",
        criadoEm: "2026-08-27",
      },
      {
        id: "ped_diogo_islandia",
        consultorId: C,
        clienteId: "cli_diogo",
        destino: "Islândia",
        dataInicio: "2026-03-06",
        dataFim: "2026-03-11",
        adultos: 2,
        criancas: 0,
        orcamento: 3000,
        mensagem: "Auroras boreais, cinco dias.",
        estado: "perdido",
        origem: "formulario",
        criadoEm: "2025-12-19",
      },
    ],

    propostas: [
      {
        id: "prop_ana_maldivas",
        consultorId: C,
        clienteId: "cli_ana",
        pedidoId: "ped_ana_maldivas",
        token: "a7f3c9d21b8e4056",
        titulo: "Maldivas, devagar",
        destino: "Maldivas",
        resumo:
          "Dez dias divididos entre dois atóis: primeiro a casa sobre a água que a Ana pediu, depois uma ilha mais pequena e mais silenciosa para os últimos dias. Sem transferes de madrugada e sem marisco em lado nenhum do menu.",
        dias: [
          {
            dia: 1,
            titulo: "Lisboa → Malé → Baa",
            descricao:
              "Voo com uma escala curta em Doha e hidroavião até ao atol de Baa ao início da tarde. Chegam com o dia ainda pela frente.",
            alojamento: "Villa sobre a água, atol de Baa",
            atividades: ["Transfer de hidroavião", "Jantar na praia"],
            refeicoes: "Jantar incluído",
          },
          {
            dia: 2,
            titulo: "Não fazer nada, oficialmente",
            descricao:
              "Primeiro dia inteiro sem nada marcado. A villa tem escada direta para a água.",
            alojamento: "Villa sobre a água, atol de Baa",
            atividades: ["Snorkeling no recife da casa"],
            refeicoes: "Tudo incluído",
          },
          {
            dia: 3,
            titulo: "Hanifaru Bay",
            descricao:
              "Saída de barco de manhã cedo para nadar com mantas — novembro ainda apanha a época. Regresso à hora do almoço.",
            alojamento: "Villa sobre a água, atol de Baa",
            atividades: ["Excursão a Hanifaru Bay", "Tarde livre"],
            refeicoes: "Tudo incluído",
          },
          {
            dia: 4,
            titulo: "Spa e pôr do sol",
            descricao:
              "Massagem a dois ao fim da tarde e um cruzeiro de dhoni ao pôr do sol.",
            alojamento: "Villa sobre a água, atol de Baa",
            atividades: ["Spa (90 min)", "Cruzeiro ao pôr do sol"],
            refeicoes: "Tudo incluído",
          },
          {
            dia: 5,
            titulo: "Mudança para Raa",
            descricao:
              "Transfer de lancha rápida a meio da manhã para uma ilha mais pequena, com metade dos quartos e nenhuma animação.",
            alojamento: "Beach villa com piscina, atol de Raa",
            atividades: ["Transfer de lancha"],
            refeicoes: "Tudo incluído",
          },
          {
            dia: 6,
            titulo: "Ilha deserta",
            descricao:
              "Piquenique numa ilha só para os dois, deixados de manhã e recolhidos ao fim da tarde.",
            alojamento: "Beach villa com piscina, atol de Raa",
            atividades: ["Piquenique em ilha privada"],
            refeicoes: "Piquenique incluído",
          },
          {
            dia: 7,
            titulo: "Mergulho ou nada",
            descricao:
              "Batismo de mergulho para quem quiser; o outro fica na piscina. Sem obrigações.",
            alojamento: "Beach villa com piscina, atol de Raa",
            atividades: ["Batismo de mergulho (opcional)"],
            refeicoes: "Tudo incluído",
          },
          {
            dia: 8,
            titulo: "Aula de cozinha maldiva",
            descricao:
              "Aula com o chef, adaptada — menu sem marisco, confirmado por escrito com o resort.",
            alojamento: "Beach villa com piscina, atol de Raa",
            atividades: ["Aula de cozinha"],
            refeicoes: "Tudo incluído",
          },
          {
            dia: 9,
            titulo: "Último dia inteiro",
            descricao: "Sem nada marcado. Check-out tardio garantido até às 16h.",
            alojamento: "Beach villa com piscina, atol de Raa",
            atividades: ["Check-out tardio"],
            refeicoes: "Tudo incluído",
          },
          {
            dia: 10,
            titulo: "Regresso",
            descricao: "Lancha e voo noturno de Malé, chegada a Lisboa na manhã seguinte.",
            alojamento: "—",
            atividades: ["Transfer para Malé"],
            refeicoes: "Pequeno-almoço",
          },
        ],
        incluido: [
          "Voos Lisboa–Malé ida e volta, uma escala",
          "Todos os transfers, incluindo hidroavião",
          "9 noites em regime de tudo incluído",
          "Excursão a Hanifaru Bay e piquenique em ilha privada",
          "Spa de 90 minutos a dois",
          "Assistência 24h durante a viagem",
        ],
        naoIncluido: [
          "Seguro de viagem (proposto à parte)",
          "Mergulho com garrafa além do batismo",
          "Bebidas premium fora do pacote",
        ],
        precoTotal: 8940,
        moeda: "EUR",
        viajantes: 2,
        estado: "enviada",
        criadoEm: "2026-08-14",
        enviadaEm: "2026-08-15",
        geradaLocalmente: false,
      },
      {
        id: "prop_bruno_dolomitas",
        consultorId: C,
        clienteId: "cli_bruno",
        pedidoId: "ped_bruno_dolomitas",
        token: "b2e814a7c05d9f36",
        titulo: "Alta Via 1, em sete dias",
        destino: "Dolomitas",
        resumo:
          "Sete dias no troço norte da Alta Via 1, com duas noites em rifugio e as etapas mais fotogénicas ao amanhecer. Todos os jantares confirmados como vegetarianos.",
        dias: [
          {
            dia: 1,
            titulo: "Chegada a Cortina",
            descricao: "Voo para Veneza e transfer para Cortina d'Ampezzo.",
            alojamento: "Hotel boutique, Cortina",
            atividades: ["Transfer", "Briefing e revisão de equipamento"],
            refeicoes: "Jantar incluído",
          },
          {
            dia: 2,
            titulo: "Lago di Braies → Rifugio Biella",
            descricao: "Primeira etapa, com saída antes do nascer do sol no lago.",
            alojamento: "Rifugio Biella",
            atividades: ["Trilho 14 km, +900 m"],
            refeicoes: "Meia pensão",
          },
          {
            dia: 3,
            titulo: "Fanes",
            descricao: "Travessia do planalto de Fanes, a etapa mais aberta do percurso.",
            alojamento: "Rifugio Lavarella",
            atividades: ["Trilho 16 km, +700 m"],
            refeicoes: "Meia pensão",
          },
          {
            dia: 4,
            titulo: "Lagazuoi",
            descricao:
              "Subida ao Lagazuoi pelos túneis da Primeira Guerra. Pôr do sol do terraço do rifugio.",
            alojamento: "Rifugio Lagazuoi",
            atividades: ["Trilho 12 km, +1100 m", "Túneis de guerra"],
            refeicoes: "Meia pensão",
          },
          {
            dia: 5,
            titulo: "Cinque Torri",
            descricao: "Descida e travessia até às Cinque Torri, com museu ao ar livre.",
            alojamento: "Rifugio Scoiattoli",
            atividades: ["Trilho 11 km, -800 m"],
            refeicoes: "Meia pensão",
          },
          {
            dia: 6,
            titulo: "Tre Cime, ao amanhecer",
            descricao:
              "Dia de carro até às Tre Cime para a volta clássica, começada às 6h para apanhar a luz.",
            alojamento: "Hotel boutique, Cortina",
            atividades: ["Circuito das Tre Cime, 10 km"],
            refeicoes: "Pequeno-almoço",
          },
          {
            dia: 7,
            titulo: "Regresso",
            descricao: "Manhã livre em Cortina e transfer para Veneza.",
            alojamento: "—",
            atividades: ["Transfer"],
            refeicoes: "Pequeno-almoço",
          },
        ],
        incluido: [
          "Voos Lisboa–Veneza ida e volta",
          "Transfers de e para Cortina",
          "6 noites (2 em hotel, 4 em rifugio) em meia pensão vegetariana",
          "Guia de montanha nos dias 2 a 5",
          "Mapas e tracks GPS do percurso",
        ],
        naoIncluido: ["Seguro de montanha", "Almoços em trilho", "Aluguer de equipamento"],
        precoTotal: 4180,
        moeda: "EUR",
        viajantes: 2,
        estado: "aceite",
        criadoEm: "2026-06-05",
        enviadaEm: "2026-06-06",
        geradaLocalmente: false,
      },
      {
        id: "prop_carla_creta",
        consultorId: C,
        clienteId: "cli_carla",
        pedidoId: "ped_carla_creta",
        token: "c9d41f6b3a2e7180",
        titulo: "Creta com os miúdos",
        destino: "Creta",
        resumo:
          "Dez dias entre Chania e a costa sul, com trajetos de carro nunca acima de 50 minutos e uma piscina em todas as noites.",
        dias: [
          {
            dia: 1,
            titulo: "Chegada a Chania",
            descricao: "Voo direto e carro alugado no aeroporto.",
            alojamento: "Casa com piscina, Chania",
            atividades: ["Recolha do carro", "Jantar no porto veneziano"],
            refeicoes: "—",
          },
          {
            dia: 2,
            titulo: "Praia de Elafonissi",
            descricao: "Areia rosa e água pelo joelho durante 100 metros — ideal para os dois.",
            alojamento: "Casa com piscina, Chania",
            atividades: ["Elafonissi"],
            refeicoes: "Pequeno-almoço",
          },
          {
            dia: 3,
            titulo: "Dia de piscina",
            descricao: "Sem carro. Dia inteiro na casa, para recuperar.",
            alojamento: "Casa com piscina, Chania",
            atividades: ["Nada marcado"],
            refeicoes: "Pequeno-almoço",
          },
          {
            dia: 4,
            titulo: "Mercado e cidade velha",
            descricao: "Manhã no mercado municipal e tarde de gelados na cidade velha.",
            alojamento: "Casa com piscina, Chania",
            atividades: ["Mercado de Chania"],
            refeicoes: "Pequeno-almoço",
          },
          {
            dia: 5,
            titulo: "Costa sul",
            descricao: "Mudança para a costa sul, 45 minutos de carro com paragem a meio.",
            alojamento: "Hotel familiar, Plakias",
            atividades: ["Transfer curto"],
            refeicoes: "Meia pensão",
          },
          {
            dia: 6,
            titulo: "Preveli",
            descricao: "Praia do palmeiral, com rio de água doce onde os miúdos podem brincar.",
            alojamento: "Hotel familiar, Plakias",
            atividades: ["Praia de Preveli"],
            refeicoes: "Meia pensão",
          },
          {
            dia: 7,
            titulo: "Barco às grutas",
            descricao: "Passeio de barco de duas horas, curto de propósito.",
            alojamento: "Hotel familiar, Plakias",
            atividades: ["Passeio de barco"],
            refeicoes: "Meia pensão",
          },
          {
            dia: 8,
            titulo: "Dia livre",
            descricao: "Praia do hotel e piscina.",
            alojamento: "Hotel familiar, Plakias",
            atividades: ["Nada marcado"],
            refeicoes: "Meia pensão",
          },
          {
            dia: 9,
            titulo: "Regresso a Chania",
            descricao: "Volta para norte com paragem em Rethymno.",
            alojamento: "Casa com piscina, Chania",
            atividades: ["Rethymno"],
            refeicoes: "Pequeno-almoço",
          },
          {
            dia: 10,
            titulo: "Voo de regresso",
            descricao: "Entrega do carro e voo ao início da tarde.",
            alojamento: "—",
            atividades: ["Entrega do carro"],
            refeicoes: "Pequeno-almoço",
          },
        ],
        incluido: [
          "Voos diretos Lisboa–Chania, 4 pessoas",
          "Carro familiar durante 10 dias",
          "9 noites com piscina em todas as unidades",
          "Passeio de barco às grutas",
        ],
        naoIncluido: ["Seguro de viagem", "Combustível e portagens", "Refeições não indicadas"],
        precoTotal: 6120,
        moeda: "EUR",
        viajantes: 4,
        estado: "aceite",
        criadoEm: "2026-02-24",
        enviadaEm: "2026-02-25",
        geradaLocalmente: false,
      },
      {
        id: "prop_diogo_islandia",
        consultorId: C,
        clienteId: "cli_diogo",
        pedidoId: "ped_diogo_islandia",
        token: "d5a72e94c1b60f38",
        titulo: "Iceland in five days",
        destino: "Islândia",
        resumo:
          "Five nights on the south coast, timed around the aurora forecast. Client went with a cheaper package in the end.",
        dias: [
          {
            dia: 1,
            titulo: "Arrival, Reykjavík",
            descricao: "Evening flight, transfer to a design hotel downtown.",
            alojamento: "Hotel boutique, Reykjavík",
            atividades: ["Transfer"],
            refeicoes: "—",
          },
          {
            dia: 2,
            titulo: "Golden Circle",
            descricao: "Þingvellir, Geysir and Gullfoss with a private driver.",
            alojamento: "Hotel boutique, Reykjavík",
            atividades: ["Golden Circle", "Aurora watch"],
            refeicoes: "Pequeno-almoço",
          },
          {
            dia: 3,
            titulo: "South coast",
            descricao: "Waterfalls, black sand, night in Vík.",
            alojamento: "Guesthouse, Vík",
            atividades: ["Seljalandsfoss", "Reynisfjara"],
            refeicoes: "Pequeno-almoço",
          },
          {
            dia: 4,
            titulo: "Glacier lagoon",
            descricao: "Jökulsárlón and Diamond Beach.",
            alojamento: "Guesthouse, Vík",
            atividades: ["Jökulsárlón"],
            refeicoes: "Pequeno-almoço",
          },
          {
            dia: 5,
            titulo: "Return",
            descricao: "Drive back with a stop at the Sky Lagoon before the flight.",
            alojamento: "—",
            atividades: ["Sky Lagoon"],
            refeicoes: "Pequeno-almoço",
          },
        ],
        incluido: ["Flights", "4 nights", "Private driver on days 2-4"],
        naoIncluido: ["Meals", "Travel insurance"],
        precoTotal: 3480,
        moeda: "EUR",
        viajantes: 2,
        estado: "recusada",
        criadoEm: "2025-12-22",
        enviadaEm: "2025-12-23",
        geradaLocalmente: false,
      },
    ],

    viagens: [
      {
        id: "via_bruno",
        consultorId: C,
        clienteId: "cli_bruno",
        propostaId: "prop_bruno_dolomitas",
        token: "f4c8b90d27e13a65",
        titulo: "Alta Via 1, em sete dias",
        destino: "Dolomitas",
        dataInicio: "2026-09-19",
        dataFim: "2026-09-26",
        valor: 4180,
        marcos: [
          {
            id: "m1",
            titulo: "Proposta aceite",
            descricao: "Tudo confirmado. Bem-vindo a bordo.",
            data: "2026-06-09",
            estado: "feito",
          },
          {
            id: "m2",
            titulo: "Sinal pago",
            descricao: "30% do valor total.",
            data: "2026-06-12",
            estado: "feito",
          },
          {
            id: "m3",
            titulo: "Voos emitidos",
            descricao: "Bilhetes no separador de documentos.",
            data: "2026-06-20",
            estado: "feito",
          },
          {
            id: "m4",
            titulo: "Rifugios confirmados",
            descricao: "As quatro noites em montanha, com jantar vegetariano confirmado.",
            data: "2026-07-04",
            estado: "feito",
          },
          {
            id: "m5",
            titulo: "Pagamento final",
            descricao: "Restantes 70%, até 30 dias antes da partida.",
            data: "2026-08-20",
            estado: "feito",
          },
          {
            id: "m6",
            titulo: "Guia de bagagem e equipamento",
            descricao: "Lista do que levar para as noites em rifugio.",
            data: "2026-09-05",
            estado: "por_fazer",
          },
          {
            id: "m7",
            titulo: "Check-in 48h antes",
            descricao: "Tratamos nós e enviamos os cartões de embarque.",
            data: "2026-09-17",
            estado: "por_fazer",
          },
          {
            id: "m8",
            titulo: "Partida",
            descricao: "Bom caminho.",
            data: "2026-09-19",
            estado: "por_fazer",
          },
        ],
        documentos: [
          { id: "d1", nome: "Bilhetes de avião", tipo: "PDF" },
          { id: "d2", nome: "Vouchers dos rifugios", tipo: "PDF" },
          { id: "d3", nome: "Tracks GPS da Alta Via 1", tipo: "GPX" },
          { id: "d4", nome: "Itinerário completo", tipo: "PDF" },
        ],
      },
      {
        id: "via_carla",
        consultorId: C,
        clienteId: "cli_carla",
        propostaId: "prop_carla_creta",
        token: "e1b74d20a9c536f8",
        titulo: "Creta com os miúdos",
        destino: "Creta",
        dataInicio: "2026-07-11",
        dataFim: "2026-07-21",
        valor: 6120,
        marcos: [
          {
            id: "m1",
            titulo: "Proposta aceite",
            descricao: "",
            data: "2026-02-28",
            estado: "feito",
          },
          { id: "m2", titulo: "Sinal pago", descricao: "", data: "2026-03-02", estado: "feito" },
          {
            id: "m3",
            titulo: "Voos emitidos",
            descricao: "",
            data: "2026-03-10",
            estado: "feito",
          },
          {
            id: "m4",
            titulo: "Pagamento final",
            descricao: "",
            data: "2026-06-10",
            estado: "feito",
          },
          { id: "m5", titulo: "Partida", descricao: "", data: "2026-07-11", estado: "feito" },
          { id: "m6", titulo: "Regresso", descricao: "", data: "2026-07-21", estado: "feito" },
          {
            id: "m7",
            titulo: "Como correu?",
            descricao: "Um minuto a contar-nos, para afinarmos a próxima.",
            data: "2026-07-24",
            estado: "por_fazer",
          },
        ],
        documentos: [
          { id: "d1", nome: "Bilhetes de avião", tipo: "PDF" },
          { id: "d2", nome: "Voucher do carro", tipo: "PDF" },
          { id: "d3", nome: "Itinerário completo", tipo: "PDF" },
        ],
      },
    ],
  };
}
